- name: Install common packages
  become: yes
  apt:
    name:
      - acl
      - git
      - python3-pip
    state: present
    update_cache: yes

- name: Clone application code
  git:
    repo: "{{ app_repo }}"
    dest: /home/{{ default_user }}/app
    force: yes


